version: "3"
services:

  express:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-express
    environment:
      - DBWEBB_DSN=mongodb://mongodb:27017/ramverk2
      - DBWEBB_PORT=1338
    volumes:
      - ./:/app/
      - /app/node_modules/
    ports:
      - 1338:1338
    links:
      - mongodb
    command: "npm start"

  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --bind_ip_all

  node-alpine-latest-test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-node-alpine
    environment:
      - DBWEBB_DSN=mongodb://mongodb:27017/ramverk2
    volumes:
      - ./:/app/
      - /app/node_modules/
    links:
      - mongodb
    command: "npm test"

  node-alpine-8-test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-node-alpine-8
    environment:
      - DBWEBB_DSN=mongodb://mongodb:27017/ramverk2
    volumes:
      - ./:/app/
      - /app/node_modules/
    links:
      - mongodb
    command: "npm test"

  node-alpine-7-test:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-node-alpine-7
    environment:
      - DBWEBB_DSN=mongodb://mongodb:27017/ramverk2
    volumes:
      - ./:/app/
      - /app/node_modules/
    links:
      - mongodb
    command: "npm test"
